### ISSUE TITLE
 Unknown error stopped the node

### ISSUE THREAD

**Issue by illusion-py** [Concordium/Testnet4-Challenges#78] opened 2021-01-28 07:17 UTC
Good afternoon, my node has been running for over 10 days, but this morning I encountered an error that stopped the node.
The ./concordium-node command gave the same error. I had to reset all blocks and start over.
If there are few such logs, then I can provide full or short ones. My discord nickname: Justillusion # 5616

full logs: https://dropmefiles.com/yuL2k
node name: illusion-node
node id: e345f770bc9c76ea

[ee6437746a3f5ac843e280b19c388ccd9e9f8cdf218b7670a77273639a75469e-json.log](https://github.com/Concordium/Testnet4-Challenges/files/5885396/ee6437746a3f5ac843e280b19c388ccd9e9f8cdf218b7670a77273639a75469e-json.log)
![image](https://user-images.githubusercontent.com/45273136/106102449-7ef20400-6150-11eb-8385-40a4be0fb9f5.png)

**Comment by concordium-cl** [comment] 2021-01-28 07:21
Good morning illusion-py, thanks for the info and especially for proactively providing the logs! We'll look into it asap.

**Comment by abizjak** [comment] 2021-01-28 07:43
@illusion-py it looks like your node was killed which led to a database corruption. The errors you see indicate that the block state storage is corrupted, but it also looks like you managed to recover by deleting the database and restarting.

There is no indication of why the node was killed, but a likely cause is resource exhaustion of some form, either running out of memory, or running out of disk space, most likely disk space. Does this sound likely in your setup? If you have not increased the resources available to the node then the failure should happen again when it reaches current block height and the node has been running for a while (the logs accumulate over time).

**Comment by illusion-py** [comment] 2021-01-28 07:53
1 server 1 node. There is a place and the memory was not clogged.

4 vCPU Cores
8 GB RAM
200 GB SSD
![image](https://user-images.githubusercontent.com/45273136/106106716-02aeef00-6157-11eb-975a-ca707e00d5ea.png)

**Comment by abizjak** [comment] 2021-01-28 09:48
No.

Your node's last message before it was restarted was at 05:54:12 (UTC Time). It was restarted at 06:42:00 (UTC Time). There is no indication in the log of any activity in between those two timestamps, so I cannot really say much. The database is written to just after the log messages at 05:54:12, that is why I guess the most likely cause was failure of file-system operations.

Was there anything usual happening on your server around that time (05:54:12)?

**Comment by illusion-py** [comment] 2021-01-28 09:53
Can not say. I slept at this time. VPS from Contabo.com

**Comment by abizjak** [comment] 2021-01-28 13:39
Is the issue now fixed after restart?

**Comment by illusion-py** [comment] 2021-01-28 14:42
@abizjak Oh sure. I thought the logs would be useful for you.

**Comment by abizjak** [comment] 2021-01-31 07:22
@illusion-py It was very good that you included the logs. Unfortunately in this instance they did not reveal the cause of the issue.

I'd say we should close this issue now since we cannot do much about it.

**Comment by concordium-cl** [comment] 2021-02-01 07:29
Will close the issue. @illusion-py, thanks for letting us know! Please get in touch, if it happens again. :pray: :+1:

**Closed by concordium-cl** 2021-02-01 07:29 UTC
Labels: investigating
