### ISSUE TITLE
baker ıd 

### ISSUE THREAD

**Issue by brkdmn1** [Concordium/Testnet4-Challenges#277] opened 2021-02-11 08:25 UTC
when ı use this command ı get this messages and think ı'm not a baker but 

-----
brkdmn@concordium:~/Documents/concordium-software$ ./concordium-client raw GetNo                                                                                                             deInfo
Node ID: "f7cf0f1814352082"
Current local time: 1613031200
Baker ID: not a baker
Peer type: "Node"
Baker running: False
Consensus running: True
Consensus type: "Passive"
Baker committee member: False
Finalization committee member: False

-----
then ı try to add baker and see ı'm already a baker

brkdmn@concordium:~/Documents/concordium-software$ ./concordium-client baker add                                                                                                              anahtar.json --sender Dmn1 --stake 10 --out ~/.local/share/concordium/baker-cre                                                                                                             dentials.json
Using default energy amount of 3060 NRG.
Adding baker with account 3jTiP5xnoVadMsvV7B74pnLbE1WuQM2eRUCzAEc3VG1HWtMuk7.
Initial stake will be 10.000000 GTU.
Rewards will be automatically added to the baking stake.
Allowing up to 3060 NRG to be spent as transaction fee.
Confirm [yN]: y
y
Error: Account is already a baker with ID 227.

what should ı do?

**Comment by concordium-cl** [comment] 2021-02-11 08:43
Hi @brkdmn1, your node is not baking. Did you restart your node after registering as a baker? 

![baker](https://user-images.githubusercontent.com/69570978/107615917-50465400-6c4d-11eb-8c0b-1498e6b34e06.JPG)

**Comment by brkdmn1** [comment] 2021-02-11 09:08
ı also restart it 3 times. but nothng happens

in 4.0.8 version my baker ıd is shown in the dashboard. but cause of memo insufficiency ı erase the virtual machine and use a new one. now in 4.0.11 ı dont have baker ıd and cant create baker credentials file cause ı get this message :
![Ekran Alıntısı](https://user-images.githubusercontent.com/77756910/107617938-cbb20080-6c61-11eb-9883-2c50d3eb86ef.PNG)
:

**Comment by concordium-cl** [comment] 2021-02-11 10:00
Ah, okay, that's an important piece of info.

The issue might be that the account correctly generated baker keys and registered as a baker in the network on the original machine, but on the new environment, the node hasn't been (re)started to run as a baker yet. 

Could you please check that the baker keys file (`anahtar.json`) is placed correctly in your concordium-data directory on the machine where the node is running now? It should be `~/.local/share/concordium` on Unix. If it is not, place it there and restart the node.

Let me know if that helps.

**Comment by brkdmn1** [comment] 2021-02-11 10:25
anahtar.json is placed correctly in my concordium-data directory on the machine where the node is running now. ı also restart node 3 times with this setup. wait 3 days but nothing changed. here is my folder (access with winscp) :
![Ekran Alıntısı1](https://user-images.githubusercontent.com/77756910/107624912-96f77680-6c6c-11eb-89ed-913eb03a34ac.PNG)

**Comment by Jasagredo** [comment] 2021-02-11 10:45
The file with the baker keys needs to be placed in your XDG-data directory (`~/.local/share/concordium` on Linux and Mac, `%LOCALAPPDATA%\\concordium` on Windows), not in the directory where the executables are located. And it has to be named `baker-credentials.json`, no other name is allowed.

The file is automatically created when registering a baker in the path provided as an argument with `--out` so supposedly it already did, unless the argument was not provided when the baker was first registered and later calls to that same command failed and didn't write the file. Can you check that the file `baker-credentials.json` is located in the correct place? It should contain the same values as the `anahtar.json` file you mention plus an additional field `"bakerId"` which in your case should show the value `227`.

**Comment by brkdmn1** [comment] 2021-02-11 11:59
there is no baker credentials file in the folder. because ı cant run this script: ./concordium-client baker add <keys-file>.json --sender bakerAccount --stake <amountToStake> --out ~/.local/share/concordium/baker-credentials.json

when ı try to run ı get "account is already a baker with ıd 227" message

![Ekran Alıntısı4](https://user-images.githubusercontent.com/77756910/107633664-77b31600-6c79-11eb-81d5-38ece2709441.PNG)

**Comment by brkdmn1** [comment] 2021-02-11 12:04
as ı mentioned in 4.0.8 version my baker ıd is shown in the dashboard. but cause of memo insufficiency ı erase the virtual machine and create a new one. now in 4.0.11 ı dont have baker ıd and cant create baker credentials file

**Comment by concordium-cl** [comment] 2021-02-11 13:38
The short story is that a baker doesn't bake without private keys. You have lost your private baker keys when swapping machines, the update from 0.4.8 to 0.4.11 is not the cause.

Without the private baker keys, your current baker 227 can never bake again. But you have the following possibilities:

1. Remove the current baker 227 and then add it again, this time keeping the `baker-credentials.json` file safe. Note however that you will have to wait 1 week (cool down period) until the baker is removed. In this time, the staked amount is not at disposal.
 
2. Add a baker with another account and bake with the new one after only 2 epochs. Note however that the staked amount from baker 227 cannot be transferred as it is staked on that baker's account.

3. Do 2. but also remove baker 227. This means you are baking after 2 hours with a new baker and after a week you can transfer the funds from baker 227 to your new account.

**In all three cases, keep the `baker-credentials.json` safe in `~/.local/share/concordium`.**

Sounds good?

**Comment by abizjak** [comment] 2021-02-11 14:11
There is a possibility number 4 if you still have the account keys, which looks like you do.

- Generate fresh baker keys with `concordium-client baker generate-keys baker-credentials.json`
- change the keys using `concordium-client baker set-key baker-credentials.json --sender $YOUR_ACCOUNT`
- **then you have to update the `baker-credentials.json` file by adding your baker-id** The file should look somewhat like the following
```json
{
    "signatureVerifyKey": "10684f6a28e85026828c22c9bb45e52db41b3a9f1114238a344247606f762108",
    "aggregationSignKey": "6f94e07f2d8cd04a0810d89e1116f095fe0d3982c0e286bfe83f59701135979b",
    "electionPrivateKey": "cbbaf71b1a01f1ae9efa1aa4f59d641a37d6be5b2a4f1bf15ecc5eb53e3e45bc",
    "aggregationVerifyKey": "9032583c5d6e41376b442b7d3780ed97c46895d6ac49c8405aed0a92ea1177d3e0411687e019312ee1ce3e6185ea0fef142e191eacc6418ab1171736e4a66bf634dd94e5cf27b145651b276bb3d0e935cf05b4b36c4ac7f0fd5bb558224c3fa8",
    "signatureSignKey": "5ecbb04b1468e4ae7561fc22c1c102bdc62e250fa056185b32357e63904bc44d",
    "electionVerifyKey": "f1fcec637ebda55ae76ad9ae49a988d5c81bd77745c442a1e0403eb0978d878b",
       "bakerId": 227
     }
``` 
except that all the keys will be different.

**Then store this file in `~/.local/share/concordium` and restart the node.**

**Comment by brkdmn1** [comment] 2021-02-11 16:39
thank you all. ı use the 4. way and it's done. at first ı get this message:
![Ekran Alıntısı5](https://user-images.githubusercontent.com/77756910/107667341-8bbe3e00-6ca0-11eb-9b27-9a6727797b2b.PNG)

but now it's seems ok.

**Comment by abizjak** [comment] 2021-02-11 18:08
That message that you saw about incorrect keys was expected until the new keys were in effect, which took between 1 to 2 hours depending on when you sent the transaction.

**Closed** 2021-02-12 07:14 UTC
Labels: investigating
